[2024-07-28T08:03:13.601+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures manual__2024-07-28T08:03:11.893556+00:00 [queued]>
[2024-07-28T08:03:13.605+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.get_pictures manual__2024-07-28T08:03:11.893556+00:00 [queued]>
[2024-07-28T08:03:13.605+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-07-28T08:03:13.605+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-07-28T08:03:13.605+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-07-28T08:03:13.611+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): get_pictures> on 2024-07-28 08:03:11.893556+00:00
[2024-07-28T08:03:13.613+0000] {standard_task_runner.py:52} INFO - Started process 396 to run task
[2024-07-28T08:03:13.615+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_pictures', 'manual__2024-07-28T08:03:11.893556+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/rocket.py', '--cfg-path', '/tmp/tmpqze2537r', '--error-file', '/tmp/tmpxs1def3g']
[2024-07-28T08:03:13.616+0000] {standard_task_runner.py:80} INFO - Job 5: Subtask get_pictures
[2024-07-28T08:03:13.642+0000] {task_command.py:371} INFO - Running <TaskInstance: download_rocket_launches.get_pictures manual__2024-07-28T08:03:11.893556+00:00 [running]> on host 82875c12dd4e
[2024-07-28T08:03:13.741+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=get_pictures
AIRFLOW_CTX_EXECUTION_DATE=2024-07-28T08:03:11.893556+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-28T08:03:11.893556+00:00
[2024-07-28T08:03:13.742+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket.py", line 34, in _get_pictures
    with open("/tmp/launches.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/launches.json'
[2024-07-28T08:03:13.746+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_pictures, execution_date=20240728T080311, start_date=20240728T080313, end_date=20240728T080313
[2024-07-28T08:03:13.750+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task get_pictures ([Errno 2] No such file or directory: '/tmp/launches.json'; 396)
[2024-07-28T08:03:13.755+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-28T08:03:13.775+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
