[2024-07-28T08:41:33.461+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.now_path manual__2024-07-28T08:41:32.954676+00:00 [queued]>
[2024-07-28T08:41:33.466+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.now_path manual__2024-07-28T08:41:32.954676+00:00 [queued]>
[2024-07-28T08:41:33.466+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-07-28T08:41:33.466+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-07-28T08:41:33.466+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-07-28T08:41:33.472+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): now_path> on 2024-07-28 08:41:32.954676+00:00
[2024-07-28T08:41:33.476+0000] {standard_task_runner.py:52} INFO - Started process 820 to run task
[2024-07-28T08:41:33.478+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'now_path', 'manual__2024-07-28T08:41:32.954676+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/rocket.py', '--cfg-path', '/tmp/tmprjbvdkku', '--error-file', '/tmp/tmpbsp35mkl']
[2024-07-28T08:41:33.479+0000] {standard_task_runner.py:80} INFO - Job 15: Subtask now_path
[2024-07-28T08:41:33.514+0000] {task_command.py:371} INFO - Running <TaskInstance: download_rocket_launches.now_path manual__2024-07-28T08:41:32.954676+00:00 [running]> on host 82875c12dd4e
[2024-07-28T08:41:33.687+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=now_path
AIRFLOW_CTX_EXECUTION_DATE=2024-07-28T08:41:32.954676+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-28T08:41:32.954676+00:00
[2024-07-28T08:41:33.688+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-07-28T08:41:33.688+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'ls -l /Users']
[2024-07-28T08:41:33.694+0000] {subprocess.py:85} INFO - Output:
[2024-07-28T08:41:33.698+0000] {subprocess.py:92} INFO - ls: cannot access '/Users': No such file or directory
[2024-07-28T08:41:33.698+0000] {subprocess.py:96} INFO - Command exited with return code 2
[2024-07-28T08:41:33.706+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-28T08:41:33.708+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=now_path, execution_date=20240728T084132, start_date=20240728T084133, end_date=20240728T084133
[2024-07-28T08:41:33.713+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task now_path (Bash command failed. The command returned a non-zero exit code 2.; 820)
[2024-07-28T08:41:33.749+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-28T08:41:33.773+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
