[2024-07-28T08:39:42.991+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.download_launches manual__2024-07-28T08:39:41.286859+00:00 [queued]>
[2024-07-28T08:39:42.996+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.download_launches manual__2024-07-28T08:39:41.286859+00:00 [queued]>
[2024-07-28T08:39:42.996+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-07-28T08:39:42.996+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-07-28T08:39:42.996+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-07-28T08:39:43.001+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): download_launches> on 2024-07-28 08:39:41.286859+00:00
[2024-07-28T08:39:43.004+0000] {standard_task_runner.py:52} INFO - Started process 796 to run task
[2024-07-28T08:39:43.005+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'download_launches', 'manual__2024-07-28T08:39:41.286859+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/rocket.py', '--cfg-path', '/tmp/tmphji0rud4', '--error-file', '/tmp/tmp2sr8zy8j']
[2024-07-28T08:39:43.006+0000] {standard_task_runner.py:80} INFO - Job 14: Subtask download_launches
[2024-07-28T08:39:43.035+0000] {task_command.py:371} INFO - Running <TaskInstance: download_rocket_launches.download_launches manual__2024-07-28T08:39:41.286859+00:00 [running]> on host 82875c12dd4e
[2024-07-28T08:39:43.143+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=download_launches
AIRFLOW_CTX_EXECUTION_DATE=2024-07-28T08:39:41.286859+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-28T08:39:41.286859+00:00
[2024-07-28T08:39:43.144+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-07-28T08:39:43.144+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', "curl -o /Users/joonhyounglee/Develop/data_temp/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-07-28T08:39:43.148+0000] {subprocess.py:85} INFO - Output:
[2024-07-28T08:39:43.155+0000] {subprocess.py:92} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-07-28T08:39:43.155+0000] {subprocess.py:92} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-07-28T08:39:43.867+0000] {subprocess.py:92} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2024-07-28T08:39:44.560+0000] {subprocess.py:92} INFO - Warning: Failed to create the file
[2024-07-28T08:39:44.563+0000] {subprocess.py:92} INFO - Warning: /Users/joonhyounglee/Develop/data_temp/launches.json: No such file or
[2024-07-28T08:39:44.564+0000] {subprocess.py:92} INFO - Warning: directory
[2024-07-28T08:39:44.565+0000] {subprocess.py:92} INFO -   5 27120    5  1360    0     0    967      0  0:00:28  0:00:01  0:00:27   967
[2024-07-28T08:39:44.565+0000] {subprocess.py:92} INFO - curl: (23) Failure writing output to destination
[2024-07-28T08:39:44.566+0000] {subprocess.py:96} INFO - Command exited with return code 23
[2024-07-28T08:39:44.589+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-07-28T08:39:44.593+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=download_launches, execution_date=20240728T083941, start_date=20240728T083942, end_date=20240728T083944
[2024-07-28T08:39:44.605+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task download_launches (Bash command failed. The command returned a non-zero exit code 23.; 796)
[2024-07-28T08:39:44.630+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-28T08:39:44.659+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
